In [ ]:
#variable
a=10
print("I am", a, "years old")

I am 10 years old


In [ ]:
# logical and operator
a = 10
b = 20
c = -10
if a > 0 and b > 0:
    print(a,"and",b,"are greater than 0")
if a > 0 and b > 0 and c > 0:
    print("The numbers are greater than 0")
else:
    print(c," is less than 0")

10 and 20 are greater than 0
-10  is less than 0


In [ ]:
#arthematic operations on two integer variables
a=int(input("Enter 1 number "));
b=int(input("Enter 2 number "));
sum=(a+b);
difference=a-b;
product=a*b;
quotient=a/b;
remainder=a%b;
power=a**b;
print(sum);
print(difference);
print(product);
print(quotient);
print(remainder);
print(power);


Enter 1 number 9
Enter 2 number 2
11
7
18
4.5
1
81


In [ ]:
#take salary from user.If salary is more than 50% there is a 10% tax print his final salary
sal=int(input("enter salary "))
if(sal>=50000):
  print("salary after tax ",sal-(sal*(10/100)))
else:
  print("no tax")

enter salary 70000
salary after tax  63000.0


In [ ]:
a=int(input("Enter number"))
i=1;
n=int(input("Enter range"))
while(i<=n):
  print(a,"X",i,"=",a*i)
  i+=1

Enter number7
Enter range12
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
7 X 10 = 70
7 X 11 = 77
7 X 12 = 84


In [ ]:
#get the salary from the user if the salary is more than  or equal to 50000 apply 10% tax deduction,If the salry is less than 50000 apply 5% tax,If salary is more than 70000 apply 12% tax ,If salary more than 1 lakh print you are promoted to next level
salary=int(input("enter salary"));
if(salary>=100000):
  print("You are promoted to next level")
elif(salary>=70000):
  print("Salary is ",salary-(salary*(12/100)))
elif(salary>=51000):
  print("Salary is ",salary-(salary*(10/100)))
else:
  print("Salary is ",salary-(salary*(5/100)))


enter salary0
Salary is  0.0


In [ ]:
#for loop
ran=range(1,11)


In [ ]:
num=int(input("enter number"))
for i in range(1,11):
  print(num,"X",i,"=",num*i)

enter number7
7 X 1 = 7
7 X 2 = 14
7 X 3 = 21
7 X 4 = 28
7 X 5 = 35
7 X 6 = 42
7 X 7 = 49
7 X 8 = 56
7 X 9 = 63
7 X 10 = 70


In [ ]:
#list heterogenous
l1=[1,"kill",2,"chat",3.4,True]
for i in l1:
  print (i)

1
kill
2
chat
3.4
True


In [ ]:
#mutable
l1.append("Leo") #adds element at the ending of list
print(l1)

[1, 'kill', 2, 'chat', 3.4, True, 'Leo']


In [ ]:
l1.insert(4,'Joe')#listname.insert(index,element)
print(l1)

[1, 'kill', 2, 'chat', 'Joe', 'Joe', 3.4, True, 'Leo']


In [ ]:
l2=["berry",3,9]
#list1.append(element)
l1.append(l2)#adds l2 to the end of the l1
#list1.extend(list2)
l1.extend(l2)#l1=l1+l2
print(l1)

[1, 'kill', 2, 'chat', 'Joe', 'Joe', 3.4, True, 'Leo', ['berry', 3], ['berry', 3, 9], 'berry', 3, 9]


In [ ]:
l1.pop(-3)#list1.pop(index number)
print(l1)

[1, 'kill', 2, 'chat', 'Joe', 3.4, True, 'Leo', 'berry', 3]


In [ ]:
l1.remove('berry')#list1.remove(element to remove)
print(l1)

[1, 'kill', 2, 'chat', 'Joe', 3.4, True, 'Leo', 3]


In [ ]:
#list1.clear()
l1.clear()#clear all the elements in list
print(l1)

[]


In [ ]:
#create a list of 10 random integer elements ,print their squares ,save these squares in a new list
l1=[2,4,6,8,10,12,14,16,18,10]
l2=[]
for i in l1:
  l2.append(i*i)
print(l2)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 100]


In [ ]:
#List Comprehension
#newlist = [output for]
l1=[2,4,6,8,10,12,14,16,18,10]
l2=[i*i for i in l1]
print(l2)

[4, 16, 36, 64, 100, 144, 196, 256, 324, 100]


In [ ]:
#List Comprehension
#newlist = [output for condition]
l3=[23,67,12,34,69]
l4=[i*i for i in l3 if i>50]
print(l4)

[4489, 4761]


In [ ]:
#newlist = [(st of if)if (cond) else(st of else )for ]
l4=[i*i if i>50 else 'X' for i in l3]
print(l4)

['X', 4489, 'X', 'X', 4761]


In [ ]:
#take the salary from the user if salary is less than 50000,10% tax otherwise 15% tax
a=[78000,50400,34000,23000,14000]
b=[(i-(i*(10/100))) if i<50000 else (i-(i*(15/100))) for i in a]
print(b)

[66300.0, 42840.0, 30600.0, 20700.0, 12600.0]


In [ ]:
#Dictionary:
#dictname={key:val,key:val.....}
#create
dict1={"Mentor":'Jwalitha',34:'Likitha',35:'Ramya',37:'Lavanya',58:'Dhanush'}
print(dict1)

{'Mentor': 'Jwalitha', 34: 'Likitha', 35: 'Ramya', 37: 'Lavanya', 58: 'Dhanush'}


In [ ]:
#create
dict1={"Mentor":'Jwalitha',"Mentor":'Likitha',35:'Ramya',37:'Lavanya',58:'Dhanush'}
print(dict1)

{'Mentor': 'Likitha', 35: 'Ramya', 37: 'Lavanya', 58: 'Dhanush'}


In [ ]:
print(dict1.keys())#displays all keys of dictionary
print(dict1.values())#displays all the values

dict_keys(['Mentor', 35, 37, 58])
dict_values(['Likitha', 'Ramya', 'Lavanya', 'Dhanush'])


In [ ]:
print(dict1[37])#To print only single value

Lavanya


In [ ]:
dict3={"class":"CSE","details":{"year":"II",'Sec':"D","Count":71}}
print("Section is",dict3["details"]["Sec"])
print("Year is",dict3["details"]["year"])
print("Count is",dict3["details"]["Count"])

Section is D
Year is II
Count is 71


In [ ]:
idl=[34,56,78,39,100]
names=["Joe","Suji","Shankar","Rohini","Mani"]
new_zip=(zip(idl,names))
for i in new_zip:
         print(i)

(34, 'Joe')
(56, 'Suji')
(78, 'Shankar')
(39, 'Rohini')
(100, 'Mani')


In [ ]:
idl = [34,56,78,39,100]
names = ["Joe","Suji","Shankar","Rohini","Mani"]
new_dict = dict(zip(idl,names))
print(new_dict)

TypeError: 'zip' object is not callable

In [ ]:
import numpy as np
A = np.array([1,2,3,4]) #1d array
print(A.ndim)
print(A.shape)

1
(4,)


In [ ]:
import numpy as np
A = np.array([[1,2,3],[4,5,6],[7,8,9]])#2d array
#elements in each row = columns
print(A)
print(A.ndim)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)


In [ ]:
import numpy as np
A = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[1,2,3]]])#3d array
#elements in each row = columns
print(A)
print(A.ndim)
print(A.shape)

[[[1 2 3]
  [4 5 6]]

 [[7 8 9]
  [1 2 3]]]
3
(2, 2, 3)


In [ ]:
A = np.ones((2,3))
print(A)

[[1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
A = np.zeros((2,3,4))
print(A)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [ ]:
A = np.eye(4)
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A = np.arange(1,10)
print(A)
print(type(A))

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [ ]:
A = np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by 8 using range function b/w 1 and 1000
A = np.arange(8,1001,8)
print(A)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
A = np.linspace(48,59,10)#np.linspace(upperlimit,lowerlimit,n)
#spliting a range into n numbers with come differences
print(A)

[48.         49.22222222 50.44444444 51.66666667 52.88888889 54.11111111
 55.33333333 56.55555556 57.77777778 59.        ]


In [ ]:
#tuples,set,documentation,qr codes,

In [ ]:
# Creating a Tuple
Tuple1 = tuple('MARVEL')
print("\nTuple is: ")
print(Tuple1)


Tuple is: 
('M', 'A', 'R', 'V', 'E', 'L')


In [ ]:
# Creating a Tuple
l1=[1,2,3,4,5,6]
print("\nTuple is : ")
print(tuple(l1))


Tuple is : 
(1, 2, 3, 4, 5, 6)


In [ ]:
#creating a tuple
#from empty tuple
Tuple=()
print("\nTuple :")
print(Tuple)



Tuple :
()


In [ ]:
t=("blue","red","yellow")
print(t[0])

blue


In [ ]:
t=("class","section","college")
print(t[-1])

college


In [ ]:
t=(1,2,3,"keyboard","phone","laptop")
print(len(t))

6


In [ ]:
a=("phone","laptop","mouse")
b=(1,2,"keyboard")
print(a+b)

('phone', 'laptop', 'mouse', 1, 2, 'keyboard')


In [ ]:
a=("class","Marvel")
b=("captain","tonny")
print(a*1)
print(b*3)

('class', 'Marvel')
('captain', 'tonny', 'captain', 'tonny', 'captain', 'tonny')


In [ ]:
t=(94,54,34,8,78)
print(max(t))

94


In [ ]:
t=(94,54,34,8,78)
print(min(t))

8


In [ ]:
#removing element from tuple
T=("a","b","c","d")
l=list(T)
print(l)
l.remove("c")
T=tuple(l)
print(T)

['a', 'b', 'c', 'd']
('a', 'b', 'd')


In [ ]:
#add element to tuple
T=("a","b","c","d")
l=list(T)
l.append("Tonny")
T=tuple(l)
print(T)

('a', 'b', 'c', 'd', 'Tonny')


In [1]:
# set
s = {'r','dbms','java','oops'}
s.add('c')
print( s)

{'r', 'java', 'oops', 'c', 'dbms'}


In [ ]:
s.remove('oops')
print(s)

{'java', 'c', 'r', 'dbms'}


In [ ]:
s.pop()
print(s)

{'c', 'r', 'dbms'}


In [ ]:
s.clear()
print(s)

set()


In [ ]:
s1={"tarun","Captain","Tonny"}
s2={"Marvel"}
s1.update(s2)
print(s1)

{'tarun', 'Marvel', 'Tonny', 'Captain'}


In [ ]:
s1={123,"tarun","Captain","Tonny","Marvel"}
s1.discard(123)
print(s1)

{'Captain', 'tarun', 'Marvel', 'Tonny'}


In [ ]:
s={1,2,3,4,5,6}
print(len(s))

6


In [ ]:
s={"tarun","Captain","Tonny","Marvel"}
s1={1,2,3,4}
s.update(s1)
print(s)

{1, 2, 3, 4, 'Marvel', 'Tonny', 'Captain', 'tarun'}


In [ ]:
s={"a","tarun","Captain","Tonny","Marvel"}
s.pop()
print(s)

{'Captain', 'tarun', 'Marvel', 'Tonny'}


In [ ]:
s={"a","Captain","Tonny","Marvel"}
s.remove("a")
print(s)

{'Marvel', 'Tonny', 'Captain'}


In [ ]:
s={1,2,3,4}
print(type(s))

<class 'set'>


In [ ]:
a = [8,6,7,12,3,5]
a.sort()
print(a)

[3, 5, 6, 7, 8, 12]


In [ ]:
a = [8,6,7,12,3,5]
b=sorted(a)
print(b)

[3, 5, 6, 7, 8, 12]


In [ ]:
a = (8,6,7,12,3,5)
b=sorted(a)
print(a)
print(b)

(8, 6, 7, 12, 3, 5)
[3, 5, 6, 7, 8, 12]


In [ ]:
a = (8,6,7,12,3,5)
a.sort()
print(a)

AttributeError: 'tuple' object has no attribute 'sort'