In [ ]:
import numpy as np
A = np.arange(1,13).reshape(3,4)
print(A)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
A = np.linspace(20,40,8).reshape(2,4)
print(A)

[[20.         22.85714286 25.71428571 28.57142857]
 [31.42857143 34.28571429 37.14285714 40.        ]]


In [ ]:
B= np.array([45,67,89,12,34,51,90,98]).reshape(2,2,2)
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
B= np.array([45,67,89,12,34,51,90,98])
B.resize(2,2,2)#changes the shape of original array
#reshape - changes needs saving in another variable
print(B)

[[[45 67]
  [89 12]]

 [[34 51]
  [90 98]]]


In [ ]:
A = np.array([34,56,78,90])
B = np.array([7,9,3,12])#list will throw an error while arrays iterate themselves
C = A-B
print(A-B)

[27 47 75 78]


In [ ]:
A = np.array([34,56,78,90])
B = np.array([7,9,3,12])#list will throw an error while arrays iterate themselves
C = A+B
print(A+B)

[ 41  65  81 102]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________________________")
print(B)
print('______________________________')
C=A*B   #one on one multication
print(C)

[[34 56]
 [78 90]]
______________________________
[[ 7  9]
 [ 3 12]]
______________________________
[[ 238  504]
 [ 234 1080]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________________________")
print(B)
print('______________________________')
C=A@B      #matrix multication
print(C)

[[34 56]
 [78 90]]
______________________________
[[ 7  9]
 [ 3 12]]
______________________________
[[ 406  978]
 [ 816 1782]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________________________")
print(B)
print('______________________________')
C=A.dot(B)#matrix multication
print(C)

[[34 56]
 [78 90]]
______________________________
[[ 7  9]
 [ 3 12]]
______________________________
[[ 406  978]
 [ 816 1782]]


In [ ]:
A = np.array([34.2,56.7,78.2,90.9,90.8])
print(A.max())# max and min only accepts numeric datatypes int and float
print(A.min())

90.9
34.2


In [ ]:
A = np.array([34,56,78,90,16,78,32,19,14,23,97,11]).reshape(4,3)
#B = np.array([7,9,3,12]).reshape(2,2)
print(A)
#print("______________________________")
#print(B)
print('______________________________')
print(A.max(axis=0))# axis =0 -column
print('______________________________')
print(A.max(axis=1))# axis =1 -row

[[34 56 78]
 [90 16 78]
 [32 19 14]
 [23 97 11]]
______________________________
[90 97 78]
______________________________
[78 90 32 97]


In [ ]:
#joining Arrays
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________________________")
print(B)
print("After vertically stacking the arrays")
print(np.vstack((A,B)))

[[34 56]
 [78 90]]
______________________________
[[ 7  9]
 [ 3 12]]
After vertically stacking the arrays
[[34 56]
 [78 90]
 [ 7  9]
 [ 3 12]]


In [ ]:
#joining Arrays
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________________________")
print(B)
print("After horizontal stacking the arrays")
print(np.hstack((A,B)))

[[34 56]
 [78 90]]
______________________________
[[ 7  9]
 [ 3 12]]
After horizontal stacking the arrays
[[34 56  7  9]
 [78 90  3 12]]


In [ ]:
A = np.array([34,56,78,90]).reshape(2,2)
B = np.array([7,9,3,12]).reshape(2,2)
print(A)
print("______________________________")
print(B)
print("After stacking the arrays")
print(np.stack((A,B),axis=0))#vertical stack
print("____________________________________")
#print(np.stack((A,B),axis=1))#horizontal stack

[[34 56]
 [78 90]]
______________________________
[[ 7  9]
 [ 3 12]]
After stacking the arrays
[[[34 56]
  [78 90]]

 [[ 7  9]
  [ 3 12]]]
____________________________________


In [ ]:
A = np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A)) #no of rows --> no of groups
#no of col in every group --> no .of rows in every group


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A = np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,5))#spliting of array into 3 arrays (1st-(0 to 2)index,2nd-(3 to 5)index number,3rd - remaining index)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]]),
 array([[15, 16, 17]])]

In [ ]:
#splitting arrays
A = np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,3)#spliting of array into 3 arrays

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[12, 13, 14],
        [15, 16, 17]])]

In [ ]:
#splitting arrays
A = np.arange(18).reshape(6,3)
print(A)
print("After splitting")
np.vsplit(A,(2,3))#vertical splitting

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting


[array([[0, 1, 2],
        [3, 4, 5]]),
 array([[6, 7, 8]]),
 array([[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]])]

In [ ]:
A = np.arange(36).reshape(6,6)
print(A)
print("After splitting")
np.hsplit(A,(3))#horizontal splitting

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print("After splitting")
np.hsplit(A,(2,5))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting


[array([[ 0,  1],
        [ 6,  7],
        [12, 13]]),
 array([[ 2,  3,  4],
        [ 8,  9, 10],
        [14, 15, 16]]),
 array([[ 5],
        [11],
        [17]])]

In [ ]:
A = np.arange(18).reshape(3,6)
print(A)

print(A.argmax(axis = 0))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[2 2 2 2 2 2]


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmax())#return the index of the maximum number


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
17


In [ ]:
A = np.array([17,4,18,56,12,33,89,21,34,55,11,13])
print(A)
print(A.argmax())# returns maximum number in the array

[17  4 18 56 12 33 89 21 34 55 11 13]
6


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmax(axis = 0))# returns maximum number in each column
print(A.argmax(axis = 1))#returns maximumn number in each row

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[2 2 2 2 2 2]
[5 5 5]


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmin())#return the index of the minimum number


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
0


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmin(axis = 0))# returns minimum number in each column
print(A.argmin(axis = 1))#returns minimumn number in each row

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
[0 0 0 0 0 0]
[0 0 0]


In [ ]:
A = np.arange(18).reshape(3,6)
print(A)
print(A.argmin())#return the index of the minimum number

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
0


In [ ]:
A = np.array([17,4,18,56,12,33,89,21,34,55,11,13])
print(A)
print(A.argmin())# returns minimum number in the array

[17  4 18 56 12 33 89 21 34 55 11 13]
1


In [ ]:
#mean,median,std,variance
A = np.array([12,34,25,66,71,88])
print("Mean ",np.mean(A))
print("Median ",np.median(A))
print("Variance ",np.var(A))
print("Standard Deviation ",np.std(A))

Mean  49.333333333333336
Median  50.0
Variance  743.888888888889
Standard Deviation  27.274326552435515


In [ ]:
#trigonometry
A = np.pi
print(A)#In radian

3.141592653589793


In [ ]:
np.rad2deg(A) #In degrees

180.0

In [ ]:
A = [np.pi/4,np.pi/3,np.pi/2,np.pi]
print(A)#In radians
print(np.rad2deg(A)) #In degrees

[0.7853981633974483, 1.0471975511965976, 1.5707963267948966, 3.141592653589793]
[ 45.  60.  90. 180.]


In [ ]:
#degrees are converted to radians
C = np.array([0,30,45,60,90,120,180])
print(np.deg2rad(C))

[0.         0.52359878 0.78539816 1.04719755 1.57079633 2.0943951
 3.14159265]


In [3]:
import numpy as np
C = np.array([0,30,45,60,90,120,180])
print(np.sin(C)) # sin values
print(np.cos(C)) # cos values
print(np.tan(C)) #tan values
print(np.arcsin(C)) #1/sin values
print(np.arccos(C))#1/cos values
print(np.arctan(C))#1/tan values

[ 0.         -0.98803162  0.85090352 -0.30481062  0.89399666  0.58061118
 -0.80115264]
[ 1.          0.15425145  0.52532199 -0.95241298 -0.44807362  0.81418097
 -0.59846007]
[ 0.         -6.4053312   1.61977519  0.32004039 -1.99520041  0.71312301
  1.33869021]
[ 0. nan nan nan nan nan nan]
[1.57079633        nan        nan        nan        nan        nan
        nan]
[0.         1.53747533 1.54857776 1.5541312  1.55968567 1.56246319
 1.56524083]


<ipython-input-3-f48a6e351cd3>:6: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(C)) #1/sin values
<ipython-input-3-f48a6e351cd3>:7: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(C))#1/cos values


In [ ]:
np.sin(C) # sin values

array([ 0.        , -0.98803162,  0.85090352, -0.30481062,  0.89399666,
        0.58061118, -0.80115264])

In [4]:
np.cos(C) # cos values

array([ 1.        ,  0.15425145,  0.52532199, -0.95241298, -0.44807362,
        0.81418097, -0.59846007])

In [ ]:
np.tan(C) #tan values

array([ 0.        , -6.4053312 ,  1.61977519,  0.32004039, -1.99520041,
        0.71312301,  1.33869021])

In [ ]:
np.arcsin(C) #1/sin values

<ipython-input-99-dd10ec83f2fb>:1: RuntimeWarning: invalid value encountered in arcsin
  np.arcsin(C) #cosec values


array([ 0., nan, nan, nan, nan, nan, nan])

In [ ]:
np.arccos(C)#1/cos values

<ipython-input-100-a16d65da514c>:1: RuntimeWarning: invalid value encountered in arccos
  np.arccos(C)


array([1.57079633,        nan,        nan,        nan,        nan,
              nan,        nan])

In [ ]:
np.arctan(C)#1/tan values

array([0.        , 1.53747533, 1.54857776, 1.5541312 , 1.55968567,
       1.56246319, 1.56524083])

In [ ]:
a =8
b =6
print(np.hypot(a,b)) #hypothesis

10.0


In [ ]:
#searching element
A = np.array([90,3,45,21,34,90,21])
print(np.where(A==90)) #returns the indexes of the number

(array([0, 5]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A%2==0)) #even numbers indexes

(array([0, 4, 5]),)


In [ ]:
A = np.array([90,3,45,21,34,90,21])
print(np.where(A>25)) # returns the numbers index which is greater than 25

(array([0, 2, 4, 5]),)


In [ ]:
import numpy as np
#searching elements in array
A = np.array([4,5,6,12,18])
print(np.searchsorted(A,12)) #outputs the index of a sorted element

3


Linear Algebra and Ufunction

In [5]:
import numpy as np
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.add(A,B)) #adding two arrays
print(np.subtract(A,B))#subtracting two arrays (first -second)
print(np.divide(A,B)) # dividing two arrays
print(np.mod(A,B)) #modulus of two arrays
print(np.divmod(A,B)) # both diving and modulus of two arrays are done first divide array and next modulus array

[12 28 70 17 22]
[ 0 20 50  7 14]
[1.  6.  6.  2.4 4.5]
[0 0 0 2 2]
(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


In [ ]:
A = np.array([6,12,34,56,9,10])
print(np.diff(A)) # subtracing two numbers in array(second-first)

[  6  22  22 -47   1]


In [ ]:
print(np.divide(A,B)) # dividing two arrays

[1.  6.  6.  2.4 4.5]


In [ ]:
print(np.mod(A,B)) #modulus of two arrays

[0 0 0 2 2]


In [ ]:
print(np.divmod(A,B)) # both diving and modulus of two arrays are done first divide array and next modulus array

(array([1, 6, 6, 2, 4]), array([0, 0, 0, 2, 2]))


Sort

In [ ]:
A =np.array([6,24,60,12,18])
print(np.sort(A))

[ 6 12 18 24 60]


Set Functions

In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.union1d(A,B))

[ 4  5  6 10 12 18 24 60]


In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.setdiff1d(A,B))

[12 18 24 60]


In [ ]:
A = np.array([6,24,60,12,18])
B = np.array([6,4,10,5,4])
print(np.intersect1d(A,B))

[6]


Rounding

In [6]:
import numpy as np
print(np.around(3.16626,4))
print(np.trunc([-3.1666,3.6666]))
print(np.fix([-3.1666,3.6666]))
print(np.floor([-3.1666,3.6666]))
print(np.ceil([-3.1666,3.1]))

3.1663
[-3.  3.]
[-3.  3.]
[-4.  3.]
[-3.  4.]


More functions

In [ ]:
A = np.array([3,4,16,19,10])
print(np.cumsum(A)) #cummulative sum of array in order

[ 3  7 23 42 52]


In [ ]:
A = np.array([3,4,16,19,10])
print(np.cumprod(A))  #cummulative product of array in order

[    3    12   192  3648 36480]


In [ ]:
print(np.lcm(34,56)) #lcm of two numbers
print(np.gcd(455,665)) #gcd of two numbers

952
35


In [ ]:
Ar = np.array([45,65,30])
print(np.lcm.reduce(Ar))

1170


In [ ]:
Ar = np.array([45,65,30])
print(np.gcd.reduce(Ar))

5


In [ ]:
a = np.array([[1,2],[3,4]])
print(np.linalg.inv(a))

[[-2.   1. ]
 [ 1.5 -0.5]]


Random

In [ ]:
from numpy import random as rd

In [ ]:
A = rd.rand() #rand(n) #default limit 0 to 0.99 for rand function
print(A)

0.2116349363152491


In [ ]:
A = rd.randintA = rd.rand() #n #default limit 0 to 0.99 for rand function
print(A) #randint(limit)==>limit 0,1,2,3,4

2


In [11]:
from numpy import random as rd
A = rd.randint(50,size=6) #limit,size
print(A)

[33 41 26 17  1 27]


In [ ]:
A = rd.randint(50,size=(2,3)) #limit
print(A)

[[20 23 35]
 [11  7 20]]


In [ ]:
A = rd.rand(10) #n #default limit 0 to 0.99
print(A)

[0.98038446 0.93892811 0.51171097 0.86502976 0.40795637 0.62606264
 0.0038921  0.48536352 0.49155007 0.13015991]


Joins

In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
#(1*4+2*5+3*6)
print(np.inner(A,B))

32


In [ ]:
A = np.array([1,2,3])
B = np.array([4,5,6])
#first row (4*1 4*2 4*3)
#second row (5*1 5*2 5*3)
#third row (6*1 6*2 6*3)
print(np.outer(A,B))

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A = np.array([1,2,3])
B = np.array([3,7,8])
print(np.cross(A,B))

[-5  1  1]
